eureka:
  instance:
    prefer-ip-address: true
    instance-id: http://${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://discovery:9001/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth:9010/auth/user/current
    client:
      client-id: demo_server
      client-secret: demo
      access-token-uri: http://auth:9010/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true