server:
  port: 9081
  context-path: /manage
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      initial-size: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
  zipkin:
    base-url: http://tracing:9003/
  sleuth:
    sampler:
      percentage: 1.0